# Generated by Django 3.2.6 on 2021-08-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('married', models.CharField(blank=True, max_length=50)),
                ('dependents', models.IntegerField(blank=True, default='0')),
                ('education', models.CharField(blank=True, max_length=50)),
                ('self_employed', models.CharField(blank=True, max_length=50)),
                ('applicantincome', models.IntegerField(blank=True, default='0', null=True)),
                ('coapplicantincome', models.IntegerField(blank=True, default='0', null=True)),
                ('loanamount', models.IntegerField(blank=True, default='0', null=True)),
                ('loanamount_term', models.IntegerField(blank=True, default='0', null=True)),
                ('credit_history', models.IntegerField(blank=True, default='1', null=True)),
                ('property_area', models.CharField(blank=True, max_length=50)),
                ('loan_status', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
